### ISSUE TITLE
somma

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/ricorsione#1]
crea una funzione ricorsiva che effettua la somma di due interi

**Comment by Teodoro777** [comment]
Su due numeri che bisogna ricorrere?

**Comment by FabioZTessitore** [comment]
sei riuscito a trovare il caso ricorsivo?

**Comment by Teodoro777** [comment]
No.

2016-10-15 12:17 GMT+02:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
Il concetto che devi tenere bene a mente quando lavori con funzioni ricorsive è: "devo risolvere un problema dello stesso tipo di quello iniziale ma più piccolo o più semplice".
Ad esempio quando calcoli il fattoriale di n scrivi: n! = n * (n-1)!
In altre parole, per calcolare il fattoriale di n ti serve il fattoriale di (n-1) (problema dello stesso tipo ma più piccolo)

**Comment by Teodoro777** [comment]
Con la somma non vedo un problema..

**Comment by FabioZTessitore** [comment]
È chiaro che la somma non necessita di ricorsione. È un esercizio di
programmazione. Devi trovare un problema più semplice e usare la ricorsione

Il sabato 15 ottobre 2016, Teodoro <notifications@github.com> ha scritto:

**Comment by Teodoro777** [comment]
Più semplice della somma??

**Comment by FabioZTessitore** [comment]
Non più semplice della somma in generale. Più semplice di a + b

Il sabato 15 ottobre 2016, Teodoro <notifications@github.com> ha scritto:

**Comment by FabioZTessitore** [comment]
non c'è nessuna chiamata ricorsiva

**Comment by Teodoro777** [comment]
Prof allora non perdiamo tempo.. Spiegatemi bene a cosa mi serve la ricorsione in questo caso che non ho capito

**Comment by FabioZTessitore** [comment]
vedi il codice

**Comment by FabioZTessitore** [comment]
haha

**Comment by Teodoro777** [comment]
Ahahahah giuro che non è opera mia.. Ho modificato con il cell stesso da l'ide del sito. Forse ho fatto qualche tocco sbagliato e chissà che ha copiato... Io volevo modificare esattamente com'è adesso (stesso commento di modifica).

**Comment by FabioZTessitore** [comment]
non va ancora bene ma ci stiamo avvicinando.
Immagina che il tuo computer possa sommare solo 1

**Comment by Teodoro777** [comment]
No, non capisco in che senso possa sommare solo 1?

**Comment by FabioZTessitore** [comment]
non puoi fare `b + `
