### ISSUE TITLE
stampa al contrario

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/ricorsione#2]
stampa le cifre di un numero al contrario mediante una funzione ricorsiva

**Comment by Teodoro777** [comment]
Per stampare al contrario un numero, si parte ovviamente dall'ultima cifra si fa quel numero % 10 e poi si divide per 10 per passare alla cifra successiva per poi continuare fino alla prima cifra. Come metto questi passaggi in ricorsione!?

**Comment by FabioZTessitore** [comment]
una volta stampata l'ultima cifra e fatta la divisione per 10 hai un problema dello stesso tipo di quello iniziale ma piu' semplice (il numero è piu' corto di una cifra)
