### ISSUE TITLE
Torre di Hanoi

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/ricorsione#4]
![es5_39_parte_i](https://cloud.githubusercontent.com/assets/3002194/19549158/fdc4e388-96a2-11e6-87bb-6612860540e0.png)

**Comment by FabioZTessitore** [comment]
![es5_39_parte_ii](https://cloud.githubusercontent.com/assets/3002194/19549165/1259117a-96a3-11e6-943c-de4e8b25983e.png)

**Comment by FabioZTessitore** [comment]
![es5_39_parte_iii](https://cloud.githubusercontent.com/assets/3002194/19549175/1cc07cca-96a3-11e6-9c58-cee8e431c54b.png)

**Comment by Teodoro777** [comment]
Ovviamente ancora non va, ma ci sono vicino...

**Comment by FabioZTessitore** [comment]
ma hai assistito alla lezione in IV?

**Comment by Teodoro777** [comment]
Sì, ma perché? Non va bene?

**Comment by FabioZTessitore** [comment]
se lo fai funzionare va bene

**Comment by Teodoro777** [comment]
Vabbè secondo me il ragionamento è giusto. Perché avete tirato in ballo la lezione in IV?

**Comment by FabioZTessitore** [comment]
perché mi pareva strano che al primo tentativo tiravi fuori la soluzione haha

**Comment by Teodoro777** [comment]
Ma non è proprio impossibile... Però è difficilotto

**Comment by FabioZTessitore** [comment]
haha ho visto, attento quando passi i parametri alle funzioni

**Comment by Teodoro777** [comment]
Sì è normale che sia lì l'errore.. Tra poco aggiusto

**Comment by Teodoro777** [comment]
Devo correggere gli ultimi passi... Comunque domani me lo dovete spiegare bene perché non l'ho capito fino in fondo

**Comment by FabioZTessitore** [comment]
ok

**Comment by Teodoro777** [comment]
Prof piano e. Ancora non si trova!! Ho fatto come mi avete detto voi..

**Comment by FabioZTessitore** [comment]
non hai fatto come ho detto io haha
controlla i paletti quando fai gli spostamenti

**Comment by Teodoro777** [comment]
No prof... non capisco

**Comment by FabioZTessitore** [comment]
hai sbagliato a passare i paletti

**Comment by Teodoro777** [comment]
Fin qui c'ero arrivato..

**Comment by FabioZTessitore** [comment]
e allora?

**Comment by Teodoro777** [comment]
Non so come risolvere ora... credo di aver fatto come avete detto.

**Comment by FabioZTessitore** [comment]
```C
hanoi(num_dischi - 1, paletto_iniziale, paletto_destinazione, paletto_temporaneo);
printf("%d -> %d\n", paletto_iniziale, paletto_temporaneo);
hanoi(num_dischi - 1, paletto_temporaneo, paletto_destinazione, paletto_iniziale);
```

questo è il tuo codice. Diciamo che paletto_iniziale è 1, destinazione è 3 e temporaneo è 2.
Stai spostando (n-1) dischi dall'1 al 3, poi ne sposti uno dall'1 al 2, infine (n-1) dal 2 al 3

Scritto così ti è più chiaro?
