### ISSUE TITLE
ricorsione e ricorsione in coda

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/ricorsione#5]
Ricapitoliamo cosa succede quando viene chiamata una 
funzione ricorsiva, ad esempio fattoriale(5):

fat(5) -> 5 * fat(4)

La funzione non può effettuare il calcolo finché
non viene calcolato fat(4).

A sua volta fat(4) -> 4 * fat(3)
e così via.

In altre parole bisogna aspettare che si arrivi alla funzione
"più interna" e poi procedere a ritroso per chiudere le funzioni

![factorial](https://cloud.githubusercontent.com/assets/3002194/19612638/0c8dc718-97e8-11e6-9080-90a99437b7d8.png)

## Ricorsione in coda

Quando la chiamata ricorsiva è l'ultima istruzione
di una funzione si ottiene la ricorsione in coda.

In questi casi il compilatore puo' eseguire un'ottimizzazione
e trasformare la ricorsione in una iterazione.

**Comment by Teodoro777** [comment]
Ok

**Comment by FabioZTessitore** [comment]
hai visto il file?

**Comment by Teodoro777** [comment]
No, dove sta?

**Comment by FabioZTessitore** [comment]
la cartella somma_coda
guarda anche il makefile, c'è una novità

**Comment by FabioZTessitore** [comment]
problemi?

**Comment by Teodoro777** [comment]
No in realtà non ho potuto nemmeno leggere il da farsi perché impegnato a studiare le altre inutili materie..

**Comment by FabioZTessitore** [comment]
haha ok

**Comment by Teodoro777** [comment]
Ok cos'è .phony?

**Comment by FabioZTessitore** [comment]
letteralmente significa FALSO
Siccome la regola `clean` non serve a generare un file così chiamato, ma è solo un nome, è buona abitudine indicarla PHONY

**Comment by Teodoro777** [comment]
Alla fine a che serve?

**Comment by Teodoro777** [comment]
Procediamo ad una scrittura di codice?

**Comment by FabioZTessitore** [comment]
Immagina che ci sia un file chiamato clean nella directory. In questo caso
quando fai make clean non verrà eseguita la pulizia perché il sistema vede
il file clean e pensa che sia aggiornato (non dipende da altri file).
Se metti phony invece l'operazione verrà eseguita sempre

Il martedì 25 ottobre 2016, Teodoro <notifications@github.com> ha scritto:
